// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/gprestore/gprestore-core/internal/database"
	"github.com/gprestore/gprestore-core/internal/delivery/rest"
	"github.com/gprestore/gprestore-core/internal/delivery/rest/middleware"
	"github.com/gprestore/gprestore-core/internal/delivery/rest/route"
	"github.com/gprestore/gprestore-core/internal/repository"
	"github.com/gprestore/gprestore-core/internal/service"
	"github.com/gprestore/gprestore-core/internal/validation"
	"net/http"
)

// Injectors from injector.go:

func InjectRoute() *route.Route {
	serveMux := http.NewServeMux()
	mongoDatabase := database.NewMongoDB()
	userRepository := repository.NewUserRepository(mongoDatabase)
	authService := service.NewAuthService(userRepository)
	middlewareMiddleware := middleware.NewMiddleware(authService)
	validate := validation.New()
	userService := service.NewUserService(userRepository, validate)
	userHandler := rest.NewUserHandler(userService)
	authHandler := rest.NewAuthHandler(authService)
	storeRepository := repository.NewStoreRepository(mongoDatabase)
	storeService := service.NewStoreService(storeRepository, validate)
	storeHandler := rest.NewStoreHandler(storeService)
	itemRepository := repository.NewItemRepository(mongoDatabase)
	itemService := service.NewItemService(itemRepository, validate)
	itemHandler := rest.NewItemHandler(itemService, storeService)
	routeRoute := route.New(serveMux, middlewareMiddleware, userHandler, authHandler, storeHandler, itemHandler)
	return routeRoute
}
