package variable

const (
	ORDER_AWAITING_PAYMENT = "AWAITING_PAYMENT"
	ORDER_PAYMENT_SUCCESS  = "PAYMENT_SUCCESS"
	ORDER_COMPLETED        = "COMPLETED"
	ORDER_EXPIRED          = "EXPIRED"

	ORDER_FEE_FLAT    = "FLAT"
	ORDER_FEE_PERCENT = "PERCENT"
)
