package variable

const (
	ORDER_NOT_CONFIRMED = "NOT_CONFIRMED"
	ORDER_PENDING       = "PENDING"
	ORDER_PROCESSED     = "PROCESSED"
	ORDER_CANCELED      = "CANCELED"
	ORDER_FAILED        = "FAILED"
	ORDER_DONE          = "DONE"

	ORDER_FEE_FLAT    = "FLAT"
	ORDER_FEE_PERCENT = "PERCENT"
)
